cmake..
wupei@wupei-robot:~/Desktop/03-freedriving/RemoteApi/build$ cmake ..
CMake Error: The current CMakeCache.txt directory /home/wupei/Desktop/03-freedriving/RemoteApi/build/CMakeCache.txt is different than the directory /home/yanyanzou/Diana_7/03-freedriving/RemoteApi/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
D
CMake Error: The source "/home/wupei/Desktop/03-freedriving/RemoteApi/CMakeLists.txt" does not match the source "/home/yanyanzou/Diana_7/03-freedriving/RemoteApi/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.:
